name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  create_release:
    name: Create ZIP Package and Upload
    runs-on: ubuntu-latest
    env:
      ASSET_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
    steps:
      - uses: actions/checkout@v4

      - name: Zip plugin package
        run: |
          set -e
          make package
          mv dist/artifact-HEAD.zip dist/$ASSET_NAME

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/zip
